package app.mast.poker.core.poker

import org.junit.Assume.assumeTrue
import org.junit.Test
import java.io.File
import kotlin.random.Random

/**
 * Rebuilds PreflopEquityData by simulation. Skipped unless MAST_GENERATE=1:
 * `MAST_GENERATE=1 ./gradlew :app:testDebugUnitTest --tests '*PreflopEquityGeneratorTest*'`
 */
class PreflopEquityGeneratorTest {

    @Test
    fun generate() {
        assumeTrue(System.getenv("MAST_GENERATE") == "1")
        val rnd = Random(1)
        val trials = 60_000
        val table = HandClasses.all.joinToString(",") { h ->
            "${h.notation}:${"%.4f".format(java.util.Locale.ROOT, vsRandom(h, trials, rnd))}"
        }
        val file = File("src/main/java/app/mast/poker/core/poker/PreflopEquityData.kt")
        file.writeText(
            """
            |package app.mast.poker.core.poker
            |
            |/** Generated by PreflopEquityGeneratorTest ($trials trials per hand) — do not edit by hand. */
            |internal object PreflopEquityData {
            |    const val TABLE = "$table"
            |}
            |""".trimMargin(),
        )
        println("wrote ${file.absolutePath}")
    }

    companion object {
        /** Equity of a random combo of [h] against a random hand, over random boards. */
        fun vsRandom(h: StartingHand, trials: Int, rnd: Random): Double {
            val heroCombos = HandClasses.combosOf(h).map { c -> IntArray(2) { FastEval.index(c[it]) } }
            val cards = IntArray(9)
            val pool = IntArray(52)
            var score = 0.0
            repeat(trials) {
                val hero = heroCombos[rnd.nextInt(heroCombos.size)]
                var n = 0
                for (c in 0 until 52) if (c != hero[0] && c != hero[1]) pool[n++] = c
                // Partial Fisher–Yates: villain 2 + board 5.
                for (i in 0 until 7) {
                    val j = i + rnd.nextInt(n - i)
                    val t = pool[i]; pool[i] = pool[j]; pool[j] = t
                }
                cards[0] = hero[0]; cards[1] = hero[1]
                for (i in 0 until 5) cards[2 + i] = pool[2 + i]
                val a = FastEval.score(cards, 7)
                cards[0] = pool[0]; cards[1] = pool[1]
                val b = FastEval.score(cards, 7)
                score += if (a > b) 1.0 else if (a == b) 0.5 else 0.0
            }
            return score / trials
        }
    }
}
